replicaCount: 1

image:
  repository: flask-app
  tag: v1
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: traefik
  path: /
  pathType: Prefix